"""Step5 ASS export: wrap-up / collision-up regressions."""

from __future__ import annotations

import sys
import tempfile
import unittest
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[1]
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from subtitle.ass_export import (  # noqa: E402
    clamp_cue_ranges_cs,
    flatten_subtitle_text,
    normalize_ass_file,
    resolve_ass_alignment,
    style_alignment_and_margin_v,
    write_ass_from_srt_blocks,
)


FFMPEG_SAMPLE = """[Script Info]
; Script generated by FFmpeg/Lavc62.28.101
ScriptType: v4.00+
PlayResX: 384
PlayResY: 288
ScaledBorderAndShadow: yes
YCbCr Matrix: None

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,16,&Hffffff,&Hffffff,&H0,&H0,0,0,0,0,100,100,0,0,1,1,0,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:01.50,Default,,0,0,0,,Dong ngan
Dialogue: 0,0:00:01.40,0:00:03.00,Default,,0,0,0,,Day la mot cau dai{\\an8}
Dialogue: 0,0:00:03.00,0:00:04.00,Default,,0,0,0,,Hai dong\\Ntrong SRT
"""


class TestAssExport(unittest.TestCase):
    def test_alignment_slider_does_not_leak(self):
        self.assertEqual(resolve_ass_alignment(12), 2)
        self.assertEqual(resolve_ass_alignment(2), 2)
        self.assertEqual(resolve_ass_alignment(8), 8)

    def test_bottom_align_keeps_margin_from_bottom(self):
        align, mv = style_alignment_and_margin_v(2, 30, 16)
        self.assertEqual(align, 2)
        self.assertEqual(mv, 30)
        align8, mv8 = style_alignment_and_margin_v(8, 40, 16)
        self.assertEqual(align8, 8)
        self.assertEqual(mv8, 40)

    def test_flatten_strips_n_and_tags(self):
        self.assertEqual(
            flatten_subtitle_text("Hai dong\\Ntrong SRT {\\an8}"),
            "Hai dong trong SRT",
        )

    def test_overlap_clamp(self):
        out = clamp_cue_ranges_cs([(0, 150, "a"), (140, 300, "b")])
        self.assertEqual(out[0][1], 140)
        self.assertEqual(out[1][0], 140)

    def test_write_from_srt_no_overlap_no_n(self):
        blocks = [
            {"index": 1, "time": "00:00:00,000 --> 00:00:01,500", "text": "Dong ngan"},
            {
                "index": 2,
                "time": "00:00:01,400 --> 00:00:03,000",
                "text": "Cau dai\ndong hai",
            },
        ]
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "sub.ass"
            write_ass_from_srt_blocks(
                blocks,
                path,
                font="Arial",
                fontsize=16,
                primary="&H00FFFFFF",
                outline_colour="&H00000000",
                outline=2,
                shadow=2,
                alignment=2,
                margin_v=30,
            )
            body = path.read_text(encoding="utf8")
        self.assertIn("WrapStyle: 0", body)
        self.assertIn("Alignment, MarginL, MarginR, MarginV", body)
        self.assertIn(",2,10,10,30,1", body)
        self.assertNotIn("\\N", body)
        self.assertIn("0:00:00.00,0:00:01.40,", body)
        self.assertIn("Cau dai dong hai", body)

    def test_normalize_ffmpeg_sample(self):
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "out.ass"
            path.write_text(FFMPEG_SAMPLE, encoding="utf8")
            normalize_ass_file(
                path,
                font="Arial",
                fontsize=16,
                primary="&H00FFFFFF",
                outline_colour="&H00000000",
                outline=2,
                shadow=2,
                alignment=2,
                margin_v=30,
            )
            body = path.read_text(encoding="utf8")
        self.assertIn("WrapStyle: 0", body)
        self.assertIn(",2,10,10,30,1", body)
        self.assertNotIn("{\\an8}", body)
        self.assertNotIn("\\N", body)
        self.assertIn("0:00:00.00,0:00:01.40,", body)
        self.assertIn("Hai dong trong SRT", body)


if __name__ == "__main__":
    unittest.main()
