"""ASS burn-in helpers for Step5.

FFmpeg SRT→ASS looks fine in a text editor (no \\pos / \\an overrides) but libass
still jumps some cues:

- PlayRes 384x288 + WrapStyle 0: long lines wrap at render; Alignment 2 grows up.
- Collisions: Normal: overlapping timestamps (common after SRT ms → ASS cs) shove
  the new cue upward.
- SRT multi-line becomes \\N (same visual jump, still easy to miss).

This module writes ASS directly and normalizes headers/events so cues do not
jump from collisions. Bottom alignment (1/2/3) is kept so wrapped lines grow
*up* (libass) and stay on-screen when MarginV is small.
"""

from __future__ import annotations

import re
from pathlib import Path

# Match ffmpeg Lavc ssa defaults + FE ASS_DEFAULT_PLAY_RES_Y.
ASS_PLAY_RES_X = 384
ASS_PLAY_RES_Y = 288

_OVERRIDE_TAG_RE = re.compile(r"\{[^}]*\}")
_HTML_TAG_RE = re.compile(r"<[^>]+>")


def cs_to_ass_time(cs: int) -> str:
    cs = max(0, int(cs))
    hours, rem = divmod(cs, 360000)
    minutes, rem = divmod(rem, 6000)
    seconds, centis = divmod(rem, 100)
    return f"{hours}:{minutes:02d}:{seconds:02d}.{centis:02d}"


def ms_to_ass_time(ms: int) -> str:
    return cs_to_ass_time((max(0, int(ms)) + 5) // 10)


def ass_time_to_cs(value: str) -> int:
    text = str(value or "").strip()
    h, m, rest = text.split(":")
    if "." in rest:
        s, cs = rest.split(".", 1)
        centis = int((cs + "00")[:2])
    else:
        s, centis = rest, 0
    return int(h) * 360000 + int(m) * 6000 + int(s) * 100 + centis


def flatten_subtitle_text(text: str) -> str:
    cleaned = str(text or "").replace("\r\n", "\n").replace("\r", "\n")
    cleaned = cleaned.replace("\\N", " ").replace("\\n", " ")
    cleaned = cleaned.replace("\n", " ")
    cleaned = _OVERRIDE_TAG_RE.sub("", cleaned)
    cleaned = _HTML_TAG_RE.sub("", cleaned)
    cleaned = cleaned.replace("{", "").replace("}", "")
    cleaned = re.sub(r"\s+", " ", cleaned).strip()
    return cleaned


def resolve_ass_alignment(raw) -> int:
    """ASS numpad 1–9. UI MarginV sliders (0–100) must not leak into Alignment."""
    try:
        value = int(raw)
    except (TypeError, ValueError):
        return 2
    if 1 <= value <= 9:
        return value
    return 2


def style_alignment_and_margin_v(alignment, margin_v, fontsize) -> tuple[int, int]:
    """Return ASS Alignment + MarginV.

    Keep 1/2/3 (bottom). Libass grows extra wrap lines *up*, so a 2-line cue
    near the bottom stays inside the frame instead of clipping below.
    Mapping to 7/8/9 would grow *down* from a top offset and clip the 2nd line
    when MarginV is small.
    """
    del fontsize
    align = resolve_ass_alignment(alignment)
    try:
        mv = max(0, int(margin_v))
    except (TypeError, ValueError):
        mv = 0
    return align, mv


def clamp_cue_ranges_cs(cues: list[tuple[int, int, str]]) -> list[tuple[int, int, str]]:
    """Ensure end <= next start (ASS centiseconds) so libass collision never shifts Y."""
    if not cues:
        return []
    ordered = sorted(cues, key=lambda c: (c[0], c[1]))
    out: list[tuple[int, int, str]] = []
    for i, (start, end, text) in enumerate(ordered):
        start = max(0, int(start))
        end = max(start + 1, int(end))
        if i + 1 < len(ordered):
            next_start = max(0, int(ordered[i + 1][0]))
            if end > next_start:
                end = next_start
        if end <= start:
            continue
        out.append((start, end, text))
    return out


def _default_style_line(
    font: str,
    fontsize: int,
    primary: str,
    outline_colour: str,
    outline: int,
    shadow: int,
    alignment: int,
    margin_v: int,
) -> str:
    font_name = str(font or "Arial").replace(",", " ")
    align, mv = style_alignment_and_margin_v(alignment, margin_v, fontsize)
    return (
        f"Style: Default,{font_name},{int(fontsize)},{primary},&H000000FF,"
        f"{outline_colour},&H00000000,0,0,0,0,100,100,0,0,1,"
        f"{int(outline)},{int(shadow)},{align},10,10,{mv},1"
    )


def build_ass_document(
    events: list[tuple[int, int, str]],
    *,
    font: str,
    fontsize: int,
    primary: str,
    outline_colour: str,
    outline: int,
    shadow: int,
    alignment: int,
    margin_v: int,
) -> str:
    clamped = clamp_cue_ranges_cs(events)
    style = _default_style_line(
        font, fontsize, primary, outline_colour, outline, shadow, alignment, margin_v
    )
    lines = [
        "[Script Info]",
        "; Script generated by KiTLabs Step5",
        "ScriptType: v4.00+",
        f"PlayResX: {ASS_PLAY_RES_X}",
        f"PlayResY: {ASS_PLAY_RES_Y}",
        "WrapStyle: 0",
        "ScaledBorderAndShadow: yes",
        "YCbCr Matrix: None",
        "",
        "[V4+ Styles]",
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, "
        "BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, "
        "BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
        style,
        "",
        "[Events]",
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
    ]
    for start_cs, end_cs, text in clamped:
        body = flatten_subtitle_text(text)
        if not body:
            continue
        lines.append(
            "Dialogue: 0,"
            f"{cs_to_ass_time(start_cs)},{cs_to_ass_time(end_cs)},"
            f"Default,,0,0,0,,{body}"
        )
    lines.append("")
    return "\n".join(lines)


def write_ass_from_srt_blocks(
    blocks: list[dict],
    ass_path: Path,
    *,
    font: str,
    fontsize: int,
    primary: str,
    outline_colour: str,
    outline: int,
    shadow: int,
    alignment: int,
    margin_v: int,
    uppercase: bool = False,
) -> Path:
    events: list[tuple[int, int, str]] = []
    for block in blocks:
        time_range = str(block.get("time") or "")
        if "-->" not in time_range:
            continue
        start_s, end_s = [x.strip() for x in time_range.split("-->")]
        start_ms = _srt_time_to_ms(start_s)
        end_ms = _srt_time_to_ms(end_s)
        text = flatten_subtitle_text(str(block.get("text") or ""))
        if uppercase:
            text = text.upper()
        if not text:
            continue
        events.append(((start_ms + 5) // 10, (end_ms + 5) // 10, text))
    path = Path(ass_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        build_ass_document(
            events,
            font=font,
            fontsize=fontsize,
            primary=primary,
            outline_colour=outline_colour,
            outline=outline,
            shadow=shadow,
            alignment=alignment,
            margin_v=margin_v,
        ),
        encoding="utf8",
    )
    return path


def _srt_time_to_ms(time_str: str) -> int:
    token = str(time_str).strip().replace(".", ",")
    hms, ms = token.split(",")
    h, m, s = hms.split(":")
    return int(h) * 3600000 + int(m) * 60000 + int(s) * 1000 + int(ms)


def normalize_ass_file(
    ass_path: Path,
    *,
    font: str,
    fontsize: int,
    primary: str,
    outline_colour: str,
    outline: int,
    shadow: int,
    alignment: int,
    margin_v: int,
) -> None:
    path = Path(ass_path)
    raw = path.read_text(encoding="utf8")
    lines = raw.splitlines(keepends=True)
    if not lines:
        return
    lines = _ensure_script_info(lines)
    lines = _replace_default_style(
        lines,
        font=font,
        fontsize=fontsize,
        primary=primary,
        outline_colour=outline_colour,
        outline=outline,
        shadow=shadow,
        alignment=alignment,
        margin_v=margin_v,
    )
    lines = _sanitize_events(lines)
    path.write_text("".join(lines), encoding="utf8")


def _ensure_script_info(lines: list[str]) -> list[str]:
    in_info = False
    have = {"PlayResX": False, "PlayResY": False, "WrapStyle": False}
    values = {
        "PlayResX": f"PlayResX: {ASS_PLAY_RES_X}\n",
        "PlayResY": f"PlayResY: {ASS_PLAY_RES_Y}\n",
        "WrapStyle": "WrapStyle: 0\n",
    }
    out: list[str] = []
    info_end_idx = None
    for idx, line in enumerate(lines):
        stripped = line.strip()
        if stripped.lower() == "[script info]":
            in_info = True
            out.append(line)
            continue
        if in_info and stripped.startswith("[") and stripped.lower() != "[script info]":
            info_end_idx = len(out)
            in_info = False
        if in_info:
            key = stripped.split(":", 1)[0].strip()
            if key in values:
                out.append(values[key])
                have[key] = True
                continue
        out.append(line)
        if in_info:
            info_end_idx = len(out)

    insert_at = info_end_idx if info_end_idx is not None else 0
    missing = [values[k] for k, ok in have.items() if not ok]
    if missing:
        out[insert_at:insert_at] = missing
    return out


def _replace_default_style(lines: list[str], **style_kw) -> list[str]:
    style_line = _default_style_line(
        style_kw["font"],
        style_kw["fontsize"],
        style_kw["primary"],
        style_kw["outline_colour"],
        style_kw["outline"],
        style_kw["shadow"],
        style_kw["alignment"],
        style_kw["margin_v"],
    ) + "\n"
    for idx, line in enumerate(lines):
        if line.startswith("Style: Default,"):
            lines[idx] = style_line
            break
    return lines


def _sanitize_events(lines: list[str]) -> list[str]:
    in_events = False
    parsed: list[tuple[str, str, str]] = []
    event_idx: list[int] = []
    cues: list[tuple[int, int, str]] = []

    for idx, line in enumerate(lines):
        if line.strip() == "[Events]":
            in_events = True
            continue
        if in_events and line.startswith("["):
            in_events = False
            continue
        if not (in_events and line.startswith("Dialogue:")):
            continue
        comma_pos = [i for i, c in enumerate(line) if c == ","]
        if len(comma_pos) < 9:
            continue
        # Dialogue: Layer,Start,End,... Text after 9th comma
        # times are field 1 and 2 after "Dialogue: "
        first = comma_pos[0]
        second = comma_pos[1]
        text_start = comma_pos[8] + 1
        start_cs = ass_time_to_cs(line[first + 1 : second])
        end_cs = ass_time_to_cs(line[second + 1 : comma_pos[2]])
        prefix = line[: first + 1]
        mid = line[comma_pos[2] : text_start]
        text = flatten_subtitle_text(line[text_start:])
        event_idx.append(idx)
        parsed.append((prefix, mid, text))
        cues.append((start_cs, end_cs, text))

    if not cues:
        return lines

    for i, (start, end, text) in enumerate(cues):
        end_cs = end
        if i + 1 < len(cues) and end_cs > cues[i + 1][0]:
            end_cs = cues[i + 1][0]
        idx = event_idx[i]
        prefix, mid, _text = parsed[i]
        if end_cs <= start or not text:
            lines[idx] = ""
            continue
        newline = "\n" if lines[idx].endswith("\n") else ""
        lines[idx] = f"{prefix}{cs_to_ass_time(start)},{cs_to_ass_time(end_cs)}{mid}{text}{newline}"
    return [ln for ln in lines if ln != ""]
